### ISSUE TITLE
weird responses (despite having context)

### ISSUE THREAD

**Issue by aesthetic0001** [IntriguingTiles/cleverbot-free#10]
the conversation goes like this:
me: my name is jimmy remember that
bot: hello, tavin!
me: what is my name?
bot: i don't know
... (2 lines later)
bot: can we high five
me: why?
bot: i feel sick.

pretty sure that doesnt make sense. either its me that's not using context correctly (my context array is basically pushing user response then bot response to an array like ["user_response", "bot_response", "user_response", "bot_response"] etc.)

**Comment by dada513** [comment]
tried this on the official website, it cant remember names either

**Comment by aesthetic0001** [comment]
yeah it doesn't, however it's still weird when it just says "can we high five" then "I feel sick"
