### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by soudblox** [IntriguingTiles/cleverbot-free#13]
i think the website content changed or something? i'm on 1.1.1

and the bot keeps responding with "You can have a great chat in www.cleverbot.com" no matter what i send

**Comment by adrifcastr** [comment]
Theyre blocking user agents, just switch to `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36` or whatever and you're good

**Comment by soudblox** [comment]
oh ok thanks

**Comment by soudblox** [comment]
wait how do i change it lol, do i need to change it via source code?

**Comment by Arda1984** [comment]
I'm asking too

**Comment by IntriguingTiles** [comment]
I'll be pushing a fix once I get to my computer

**Comment by Arda1984** [comment]
ty

**Comment by JerryFunHouse** [comment]
Worked for me thanks adrif!
So for the others that are not sure what to do, go into the cleverbot-free module, open the index.js and change the two instances of "Mozilla/5.0" to "Safari/537.36", "Chrome/90.0.4430.72" or "AppleWebKit/537.36" (Line 18 and 43)
Worked for me

**Comment by Arda1984** [comment]
> Worked for me thanks adrif!
> So for the others that are not sure what to do, go into the cleverbot-free module, open the index.js and change the two instances of "Mozilla/5.0" to "Safari/537.36", "Chrome/90.0.4430.72" or "AppleWebKit/537.36" (Line 18 and 43)
> Worked for me

thank you JerryFunHouse, I replaced the 2 "Mozilla/5.0" to "Chrome/90.0.4430.72" and it worked :)

**Comment by Arda1984** [comment]
Mozilla/5.0 (Windows NT 10.0; Win64; x64) works fine too

**Comment by IntriguingTiles** [comment]
I've pushed a fix to NPM.
