### ISSUE TITLE
cleverbot-free not working / undefined

### ISSUE THREAD

**Issue by Arda1984** [IntriguingTiles/cleverbot-free#17]
In version 1.1.1, cleverbot-free gave "undefined" as the result today, when I looked at the NPM page I saw that there was a new version "1.1.2", after I updated it cleverbot-free was still giving me "undefined" as a result.
Soo is it going to be fixed today?

**Comment by Soulhackzlol** [comment]
prob, theres already a pull request so ig its just fixing that

**Comment by IntriguingTiles** [comment]
This is now fixed with version 1.1.3.
