### ISSUE TITLE
how would you get the response part to work?

### ISSUE THREAD

**Issue by Teedie** [IntriguingTiles/cleverbot-free#18]
im a beginner coder with javascript, how exactly would you get the response bit of this code to work? aka connect it to a function or something. google didn't come up with anything even remotely useful

and yes I know this is an extremely simple question but nothing else gave me a response _so here I am_
thankz in advance

**Comment by BradGamez** [comment]
On the main page, for this repository, the readme shows a usage example for you. 
https://github.com/IntriguingTiles/cleverbot-free

**Comment by Teedie** [comment]
oh, thanks. sorry for wasting your time, didn't know it'd work like that
