### ISSUE TITLE
Error: Response timeout of 5000ms exceeded.

### ISSUE THREAD

**Issue by CoderViki** [IntriguingTiles/cleverbot-free#24]
Hello,

 the previous error has been fixed. However, if it is in use for more than 40 minutes, the "Error: Response timeout of 5000ms exceded." Gives a fault.

Thanks for your help <3

**Comment by Major-Thrust** [comment]
paul is getting better at dodging our fixed 😂😂, lets see what else he got

**Comment by CoderViki** [comment]
****


Error: Service Unavailable
    at Request.callback (C:\Users\lenovo\Desktop\discord\node_modules\superagent\lib\node\index.js:883:15)
    at IncomingMessage.<anonymous> (C:\Users\lenovo\Desktop\discord\node_modules\superagent\lib\node\index.js:1126:20)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  status: 503,
  response: <ref *1> Response {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 503,
      statusMessage: 'Service Temporarily Unavailable',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [ClientRequest],
      text: '<html>\r\n' +
        '<head><title>503 Service Temporarily Unavailable</title></head>\r\n' +
        '<body bgcolor="white">\r\n' +
        '<center><h1>503 Service Temporarily Unavailable</h1></center>\r\n' +
        '<hr><center>nginx/1.14.0</center>\r\n' +
        '</body>\r\n' +
        '</html>\r\n' +
        '\r\n' +
        '\r\n' +
        '\r\n' +
        '\r\n' +
        '\r\n' +
        '\r\n',
      [Symbol(kCapture)]: false,
      [Symbol(RequestTimeout)]: undefined
    },
    request: Request {
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      _enableHttp2: false,
      _agent: false,
      _formData: null,
      method: 'POST',
      url: 'https://www.cleverbot.com/webservicemin?uc=UseOfficialCleverbotAPI&out=&in=&bot=c&cbsid=AYAF96DROY&xai=AYA&ns=1&al=&dl=&flag=&user=&mode=1&alt=0&reac=&emo=&sou=website&xed=&',
      _header: [Object],
      header: [Object],
      writable: true,
      _redirects: 0,
      _maxRedirects: 5,
      cookies: '',
      qs: {},
      _query: [],
      qsRaw: [],
      _redirectList: [],
      _streamRequest: false,
      _responseTimeout: 5000,
      _timeout: 60000,
      _data: 'stimulus=hi&vText2=Nice%20to%20meet%20you.&vText3=helloo&vText4=%7C015Eu%2520an%2520ne%2520yap%7C0131yorsun.&vText5=im%fine&vText6=%7C0130yiyim%2520sen%2520nas%7C0131ls%7C0131n.&vText7=hello&vText8=I%27m%20fine.&vText9=how%20are%20you&vText10=Fabulous%2C%20and%20you%3F&vText11=how%20are%20you&vText12=Hi%3F&vText13=hello&vText14=Why%20thank%20you.&vText15=hello&vText16=What%20is%20the%20earth%3F&vText17=&cb_settings_scripting=no&islearning=1&icognoid=wsf&icognocheck=b93877c1e37968023bfaac712264e15e',
      req: [ClientRequest],
      protocol: 'https:',
      host: 'www.cleverbot.com',
      _endCalled: true,
      _callback: [Function (anonymous)],
      _fullfilledPromise: [Promise],
      res: [IncomingMessage],
      _resBuffered: true,
      response: [Circular *1],
      called: true,
      [Symbol(kCapture)]: false
    },
    req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 550,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'POST /webservicemin?uc=UseOfficialCleverbotAPI&out=&in=&bot=c&cbsid=AYAF96DROY&xai=AYA&ns=1&al=&dl=&flag=&user=&mode=1&alt=0&reac=&emo=&sou=website&xed=& HTTP/1.1\r\n' +
        'Host: www.cleverbot.com\r\n' +
        'Accept-Encoding: gzip, deflate\r\n' +
        'Cookie: XVIS=TE1939AFFIAGAYQZA6710; _cbsid=-1\r\n' +
        'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36\r\n' +
        'Content-Type: text/plain\r\n' +
        'Content-Length: 550\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/webservicemin?uc=UseOfficialCleverbotAPI&out=&in=&bot=c&cbsid=AYAF96DROY&xai=AYA&ns=1&al=&dl=&flag=&user=&mode=1&alt=0&reac=&emo=&sou=website&xed=&',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'www.cleverbot.com',
      protocol: 'https:',
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    text: '<html>\r\n' +
      '<head><title>503 Service Temporarily Unavailable</title></head>\r\n' +
      '<body bgcolor="white">\r\n' +
      '<center><h1>503 Service Temporarily Unavailable</h1></center>\r\n' +
      '<hr><center>nginx/1.14.0</center>\r\n' +
      '</body>\r\n' +
      '</html>\r\n' +
      '\r\n' +
      '\r\n' +
      '\r\n' +
      '\r\n' +
      '\r\n' +
      '\r\n',
    body: {},
    files: undefined,
    buffered: true,
    headers: {
      server: 'nginx/1.14.0',
      date: 'Sat, 24 Apr 2021 11:15:13 GMT',
      'content-type': 'text/html',
      'content-length': '615',
      connection: 'close'
    },
    header: {
      server: 'nginx/1.14.0',
      date: 'Sat, 24 Apr 2021 11:15:13 GMT',
      'content-type': 'text/html',
      'content-length': '615',
      connection: 'close'
    },
    statusCode: 503,
    status: 503,
    statusType: 5,
    info: false,
    ok: false,
    redirect: false,
    clientError: false,
    serverError: true,
    error: Error: cannot POST /webservicemin?uc=UseOfficialCleverbotAPI&out=&in=&bot=c&cbsid=AYAF96DROY&xai=AYA&ns=1&al=&dl=&flag=&user=&mode=1&alt=0&reac=&emo=&sou=website&xed=& (503)
        at Response.toError (C:\Users\lenovo\Desktop\discord\node_modules\superagent\lib\node\response.js:98:13)
        at ResponseBase._setStatusProperties (C:\Users\lenovo\Desktop\discord\node_modules\superagent\lib\response-base.js:119:48)
        at new Response (C:\Users\lenovo\Desktop\discord\node_modules\superagent\lib\node\response.js:44:8)
        at Request._emitResponse (C:\Users\lenovo\Desktop\discord\node_modules\superagent\lib\node\index.js:930:18)
        at IncomingMessage.<anonymous> (C:\Users\lenovo\Desktop\discord\node_modules\superagent\lib\node\index.js:1126:42)
        at IncomingMessage.emit (events.js:327:22)
        at endReadableNT (_stream_readable.js:1327:12)
        at processTicksAndRejections (internal/process/task_queues.js:80:21) {
      status: 503,
      text: '<html>\r\n' +
        '<head><title>503 Service Temporarily Unavailable</title></head>\r\n' +
        '<body bgcolor="white">\r\n' +
        '<center><h1>503 Service Temporarily Unavailable</h1></center>\r\n' +
        '<hr><center>nginx/1.14.0</center>\r\n' +
        '</body>\r\n' +
        '</html>\r\n' +
        '\r\n' +
        '\r\n' +
        '\r\n' +
        '\r\n' +
        '\r\n' +
        '\r\n',
      method: 'POST',
      path: '/webservicemin?uc=UseOfficialCleverbotAPI&out=&in=&bot=c&cbsid=AYAF96DROY&xai=AYA&ns=1&al=&dl=&flag=&user=&mode=1&alt=0&reac=&emo=&sou=website&xed=&'
    },
    created: false,
    accepted: false,
    noContent: false,
    badRequest: false,
    unauthorized: false,
    notAcceptable: false,
    forbidden: false,
    notFound: false,
    unprocessableEntity: false,
    type: 'text/html',
    links: {},
    setEncoding: [Function: bound ],
    redirects: [],
    pipe: [Function (anonymous)],
    [Symbol(kCapture)]: false
  }
}

**Comment by XzFrosT** [comment]
Cleverbot developer is blocked package like this cause its break clever terms no 3, so isnt working anymore.

**Comment by insomnia-creator** [comment]
It's probably because cleverbot did not respond in enough time so it basically cancelled the operation.

Just do a simple catch statement.

```javascript
clever('stop').then(res => {console.log(res); return;}).catch(e => console.log(e);

//or

try {clever('STOP').then(res => {return res;})}
catch(e){console.log(e);}
```

**Comment by IntriguingTiles** [comment]
I increased the timeout in v1.1.6 which might help.

**Comment by CoderViki** [comment]
How can I clear the XVIS cookies? If we clear this cookie, this problem will be fixed completely.
