### ISSUE TITLE
Responses working, but timing out most of the time

### ISSUE THREAD

**Issue by RealSkyr0** [IntriguingTiles/cleverbot-free#25]
Just need to know if this is temporary or should I change my code to account for long delays?

**Comment by comicallybad** [comment]
Having same issue, the error immediately crashes my discord bot, so I made an error handler that won't crash my bot and will send me a message of the error, and I wake up to over 35 timeout errors from the superagent package. It responds sometimes, but the older version I never had the issue until they changed the API and you guys had to understandably update as it was responding with go check out cleverbot.com

**Comment by TrashUwU** [comment]
> Having same issue, the error immediately crashes my discord bot, so I made an error handler that won't crash my bot and will send me a message of the error, and I wake up to over 35 timeout errors from the superagent package. It responds sometimes, but the older version I never had the issue until they changed the API and you guys had to understandably update as it was responding with go check out cleverbot.com

Comically bad add me on rocket league!

**Comment by IntriguingTiles** [comment]
Closing as stale. Let me know if this is still an issue on the latest version.
