### ISSUE TITLE
503 Error

### ISSUE THREAD

**Issue by CoderViki** [IntriguingTiles/cleverbot-free#26]
Hello, I get a "503" error with heavy use. How can I fix this problem?

**Example Code:**
```js
const IntriguingTiles = require('cleverbot-free')

setInterval(function(){ 
IntriguingTiles('Hello.').then((IntriguingTiles_is_best) => {
  console.log(IntriguingTiles_is_best);
})
}, 1000);
```
**Error: Request failed with status code 503**

**Comment by CoderViki** [comment]
`   makeAIRequest: function() {
        cleverbot.aistate = 2;
        cleverbot.typeErrorWithDots(cleverbot.getTextString("thinking"), cleverbot.getTextString("stillthinking"), cleverbot.aitimeout / 2);
        if (cleverbot.debug > 0) {
            console.log("Making request " + cleverbot.numairequests + " with input " + cleverbot.input)
        }
        if (cleverbot.airequest) {
            cleverbot.airequest.abort();
            cleverbot.airequest = false
        }
        var a = new XMLHttpRequest();
        cleverbot.lineelements[0].className = cleverbot.lineelements[0].className.replace(" fallback", "");
        if (cleverbot.tryFallbackOrModification(cleverbot.getInputValue("testfallback") ? false : true)) {
            return
        }
        a.onreadystatechange = function() {
            if (cleverbot.debug > 0) {
                console.log("Request in state " + cleverbot.aistate + " ready state: " + a.readyState + ", status: " + a.status + ", len: " + a.responseText.length)
            }
            if (a.readyState != 4) {
                return
            }
            if (a.status == 200 && a.responseText.indexOf("<html>") >= 0) {
                cleverbot.abortAIRequest(0, 0)
            } else {
                if (a.status == 200) {
                    cleverbot.processAI(a.responseText, a.getResponseHeader("SC"), 0)
                } else {
                    if (a.status == 503 && cleverbot.page503 && cleverbot.num503 >= 4) {
                        document.location.href = cleverbot.page503
                    } else {
                        if (a.status == 503 || a.status == 505) {
                            cleverbot.num503++;
                            setTimeout(cleverbot.makeAIRequest, cleverbot.betweenrequests * 1000)
                        } else {
                            if (a.status == 0 || a.status == 400) {
                                cleverbot.abortAIRequest(0, 0)
                            } else {
                                if (a.status == 401) {
                                    var c = document.location.pathname + "?nocachejs=yes&lasti=" + encodeURIComponent(cleverbot.input);
                                    if (cleverbot.lines.length <= 2) {
                                        c += "&lastb=" + encodeURIComponent(cleverbot.reply)
                                    }
                                    document.location.href = c
                                } else {
                                    setTimeout(new Function("cleverbot.abortAIRequest (" + cleverbot.numairequests + ", 0);"), cleverbot.airemake * 1000)
                                }
                            }
                        }
                    }
                }
            }
        }`

Here Cleverbot 503 code's.

**Comment by IntriguingTiles** [comment]
This shouldn't be an issue on the latest version. Also, please don't post any Cleverbot code here.

**Comment by CoderViki** [comment]
This issue is still not fixed.

**Comment by IntriguingTiles** [comment]
As far as I'm aware, unless you're spamming the API, you shouldn't be getting any 503s on the latest version.

**Comment by CoderViki** [comment]
Even if I don't spam this issue occurs "after long chats".

**Comment by IntriguingTiles** [comment]
Closing as stale. Let me know if this is still an issue on the latest version.
