### ISSUE TITLE
Cleverbot Forbidden

### ISSUE THREAD

**Issue by BradGamez** [IntriguingTiles/cleverbot-free#27]
> (node:4511) UnhandledPromiseRejectionWarning: Error: Forbidden
>     at Request.callback (/AbuseV3/node_modules/superagent/lib/node/index.js:883:15)
>     at IncomingMessage.<anonymous> (/AbuseV3/node_modules/superagent/lib/node/index.js:1126:20)
>     at IncomingMessage.emit (events.js:327:22)
>     at endReadableNT (internal/streams/readable.js:1327:12)
>     at processTicksAndRejections (internal/process/task_queues.js:80:21)`

When trying to use Cleverbot. The latest version (cleverbot-free@1.1.6)

**Comment by IntriguingTiles** [comment]
You've been IP banned from Cleverbot.

**Comment by BradGamez** [comment]
Oh cool. Using proxies or changing IP time.
