### ISSUE TITLE
Cleverbot timeouts sometimes and gives answers that doesn't make any sense

### ISSUE THREAD

**Issue by Arda1984** [IntriguingTiles/cleverbot-free#28]
It timeouts sometimes and the responds taking longer than before.

Also when it responds does the answers mostly make no sense
exp when i ask "How are you" it answers "mph" or in a other language.

That came with the new update, before that everything was fine

**Comment by IntriguingTiles** [comment]
Closing as stale. Let me know if this is still an issue on the latest version.
