### ISSUE TITLE
no normal response, "You can have a great chat at www.cleverbot.com."

### ISSUE THREAD

**Issue by SpeckyYT** [IntriguingTiles/cleverbot-free#29]
I guess cleverbot owners fucked up this module.
It returns "You can have a great chat at www.cleverbot.com." on any message.

**Comment by SammyWhamy** [comment]
I'm only getting "Forbidden" error messages right now

**Comment by APartOfMe1** [comment]
I had the same error. Fixed it by just updating to the latest version of the package
`npm i cleverbot-free@latest`

**Comment by SpeckyYT** [comment]
Oh, just realised that this is an Ubuntu-only error (on my Windows machine it works).

**Comment by APartOfMe1** [comment]
It's definitely not ubuntu only. I can recreate this on windows using version 1.0.5. The fix was just updating to 1.1.6

**Comment by SpeckyYT** [comment]
I'm using 1.1.6 on Ubuntu, but I still get the same text (i.e. `You can have a great chat at www.cleverbot.com.`)

**Comment by SpeckyYT** [comment]
nvm, now it seems to work fine again.
