### ISSUE TITLE
Context Escapes!

### ISSUE THREAD

**Issue by ObliviousDonkey** [IntriguingTiles/cleverbot-free#3]
Only the last two elements of the array are considered as context! 
Me: You are a bot.
Bot: No Im not. I can prove it.
Me: Prove it!
Bot: *Forgets the first sentence(You are a robot) and gives a nonsense response*

**Comment by IntriguingTiles** [comment]
I can't seem to reproduce this with `cleverbot("Prove it.", ["You are a bot.", "No I'm not. I can prove it."]);`. I get responses like "I have feelings but you do not." which makes sense to me.

Make sure you're using the latest version of cleverbot-free as previous versions modified the context array which could cause this.

**Comment by ObliviousDonkey** [comment]
> I can't seem to reproduce this with `cleverbot("Prove it.", ["You are a bot.", "No I'm not. I can prove it."]);`. I get responses like "I have feelings but you do not." which makes sense to me.
> 
> Make sure you're using the latest version of cleverbot-free as previous versions modified the context array which could cause this.

I am using the old version XD
