### ISSUE TITLE
Bot constantly timing out after the first few messages

### ISSUE THREAD

**Issue by RealSkyr0** [IntriguingTiles/cleverbot-free#32]
As title said, bot keeps timing out after the first few messages, then after a while it starts working again and at some point starts timing out again. Is this just a cleverbot issue?
log:

![image](https://user-images.githubusercontent.com/44062109/124379084-944dfa00-dcbd-11eb-96d9-d05639161854.png)

**Comment by IntriguingTiles** [comment]
Closing as stale. Let me know if this is still an issue on the latest version.
