### ISSUE TITLE
Throws "TypeError: Cannot read properties of undefined (reading 'split')"

### ISSUE THREAD

**Issue by JstnMcBrd** [IntriguingTiles/cleverbot-free#34]
I have a constantly-running bot that depends on this node module. After few weeks, this module will begin throwing `TypeError: Cannot read properties of undefined (reading 'split')` every time a response is requested. Restarting the bot fixes the issue, at least for another couple weeks.

I suspect the error is coming from lines 52-54 of [index.js](https://github.com/IntriguingTiles/cleverbot-free/blob/master/index.js) when `req.text` is undefined. I don't know why it would be undefined, or why the error won't go away until I restart the bot.

Because of the infrequent nature of this error, it is hard to reproduce, otherwise I would provide screenshots of the error output.

**Comment by IntriguingTiles** [comment]
It's probably the XVIS cookie expiring. Shouldn't be too hard to fix.

**Comment by JstnMcBrd** [comment]
The error reappeared after exactly a month. This time I logged the error output.

![image](https://user-images.githubusercontent.com/28303477/152470714-e3a5ac73-cfbb-484e-bcd2-1b52bdc211a4.png)

**Comment by IntriguingTiles** [comment]
Could you try replacing cleverbot-free's index.js with [this](https://gist.github.com/IntriguingTiles/1c9baebff154d247cbba9bf156532257)? It'll refresh the XVIS cookie every 24 hours hours which should hopefully fix this. It'll also log some information about the request if it fails like this again.

**Comment by JstnMcBrd** [comment]
It's been a little over a month since I restarted the bot, and it's still working with no errors.

**Comment by IntriguingTiles** [comment]
Excellent. I've just pushed a new version with the fix.
