### ISSUE TITLE
Cookie error

### ISSUE THREAD

**Issue by BradGamez** [IntriguingTiles/cleverbot-free#36]
/Abuse/AbuseV3/node_modules/cleverbot-free/index.js:49
                 .set("Cookie", `${cookies[0].split(";")[0]}; _cbsid=-1`)
                                          ^
 TypeError: Cannot read properties of undefined (reading '0')
     at module.exports (/Abuse/AbuseV3/node_modules/cleverbot-free/index.js:49:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Rhythm113** [comment]
API Probably Updated

**Comment by IntriguingTiles** [comment]
I've pushed v1.1.10 to NPM which should fix this. Looks like the Cleverbot developers are interested in breaking my package again.
