### ISSUE TITLE
TypeError: _context.reverse is not a function

### ISSUE THREAD

**Issue by cph101** [IntriguingTiles/cleverbot-free#38]
Is anybody else getting this? Or at least why am I?
![IMG_1612](https://user-images.githubusercontent.com/93673699/166525610-194d5ade-f4ed-4539-8eea-73ce4cc90854.jpeg?width=400px)

**Comment by IntriguingTiles** [comment]
Whatever you're passing for the second argument is the wrong type. Pass either nothing or an array.

**Comment by cph101** [comment]
Thanks so much! Accidentally passed a string instead of an array 🤦🏼‍♂️
