### ISSUE TITLE
superagent@7.1.6 deprecation

### ISSUE THREAD

**Issue by JstnMcBrd** [IntriguingTiles/cleverbot-free#44]
I receive this warning when running `npm install`:

`npm WARN deprecated superagent@7.1.6: Please downgrade to v7.1.5 if you need IE/ActiveXObject support OR upgrade to v8.0.0 as we no longer support IE and published an incorrect patch version (see https://github.com/visionmedia/superagent/issues/1731)`.

**Comment by IntriguingTiles** [comment]
Resolved in v1.1.13
