### ISSUE TITLE
Typescript types don't import correctly when using ESM

### ISSUE THREAD

**Issue by JstnMcBrd** [IntriguingTiles/cleverbot-free#45]
I recently migrated one of my projects from JavaScript to TypeScript, and then from CommonJS to EMCAScript modules (ESM).

While you have added [types](https://github.com/IntriguingTiles/cleverbot-free/blob/master/index.d.ts) to cleverbot-free, they do not work correctly when using ESM.

Here is an example of the error I am getting.

![image](https://github.com/IntriguingTiles/cleverbot-free/assets/28303477/955dc3f7-43cb-4fcd-b163-f6289e7ba634)

As you can see, the type of `cleverbot` is not being imported correctly.

I did some research, and found some relevant threads [here](https://github.com/microsoft/TypeScript/issues/49189) and [here](https://github.com/davidjerleke/embla-carousel/issues/481).

It appears that the problem may be fixed by adding `"type": "module"` to [package.json](https://github.com/IntriguingTiles/cleverbot-free/blob/master/package.json) so the types can be interpreted as ESM types.

I modified cleverbot-free's package.json in the `node_modules` of my project, and it fixed the issue.
![image](https://github.com/IntriguingTiles/cleverbot-free/assets/28303477/afd93187-d5a9-40a0-a3fa-1812ed2d099f)
![image](https://github.com/IntriguingTiles/cleverbot-free/assets/28303477/4d92727b-5a9f-4d06-adb0-cf0b4e62080c)

As you can see, the type is now being imported correctly and TypeScript can compile.

Alternatively, you could also fix the problem by changing `export default cleverbot` to `export = cleverbot` in index.d.ts, but that might not be backwards-compatible to pre-node16 ESM versions? Not sure.

Here is an additional resource: https://arethetypeswrong.github.io/?p=cleverbot-free%401.1.12

**Comment by IntriguingTiles** [comment]
Resolved via the latter solution in v1.1.13.
