### ISSUE TITLE
Critical vulnerability in `formidable` cannot be patched

### ISSUE THREAD

**Issue by JstnMcBrd** [IntriguingTiles/cleverbot-free#52]
There is a critical vulnerability with `formidable` that cannot be patched without updating this package.

![image](https://github.com/IntriguingTiles/cleverbot-free/assets/28303477/6d9b324a-904c-4559-87ee-25bdad811d21)

This package relies on `superagent`, which relies on `formidable`.

Updating `superagent` will require updating to major version 9, because all older versions have been deprecated due to this vulnerability.

![image](https://github.com/IntriguingTiles/cleverbot-free/assets/28303477/8c7c8922-0311-4b45-9c3f-f5e72ed8ade9)

As the deprecation note warns, this will also change your `node` version compatibility.

**Comment by IntriguingTiles** [comment]
Fixed in `v2.0.3`.
