### ISSUE TITLE
Using multiple contexts

### ISSUE THREAD

**Issue by SathvikHegde** [IntriguingTiles/cleverbot-free#8]
I have been using this api in my discord bot and the bot seems and I seem to have problem with contexts. Like if I say "my name is frog" and ask the bot "what is my name" it replies with "I dont know" or something like that.

We have many things like this in our server like "tai is your master" and we make the bot remember many things like that but this api only supports one context is there a way to add multiple contexts?

Thanks.

**Comment by IntriguingTiles** [comment]
Multiple contexts can be accomplished with multiple context arrays.

**Comment by SathvikHegde** [comment]
Huh ok 
I will try that
